apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    builder: "KJW(ncs10322@naver.com)"
    buildDate: "20220819"
    imageRegistry: https://hub.docker.com
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80
