apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  clusterIP: 10.233.10.10
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
