apiVersion: batch/v1
kind: CronJob
metadata:
  name: showdate
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: showdate
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello kubernetes
          restartPolicy: OnFailure